// Generated by Rivet. Do not edit by hand.
#pragma once

#include <cstdint>
#include <exception>
#include <functional>
#include <future>
#include <optional>
#include <stdexcept>
#include <string>
#include <utility>
#include <variant>
#include <vector>

#include "backend.hpp"

namespace rivet_app {
inline constexpr char kModuleName[] = "backend";
inline constexpr char kEntryName[] = "start";
inline constexpr char kDisplayName[] = "keepsake";
inline constexpr char kVersion[] = "0.1.0";
inline constexpr std::int64_t kBuild = 1;
inline constexpr char kIdentifier[] = "dev.rivet.keepsake";
inline constexpr char kReleaseChannel[] = "stable";

struct AccountInfo {
  std::string id;
  std::string path;
  std::string size_label;
};

struct OperationResult {
  bool ok;
  std::string message;
};

struct SnapshotInfo {
  std::int64_t index;
  std::string created_at;
  std::string account;
  std::int64_t file_count;
  std::string total_label;
};

template <typename T>
struct Result {
  std::optional<T> value;
  std::exception_ptr error;
  bool succeeded() const noexcept { return value.has_value() && !error; }
  T const& get() const { if (error) std::rethrow_exception(error); if (!value) throw std::runtime_error("Rivet async result has no value"); return *value; }
};

template <>
struct Result<void> {
  std::exception_ptr error;
  bool succeeded() const noexcept { return !error; }
  void get() const { if (error) std::rethrow_exception(error); }
};

namespace detail {
inline rivet::Value encode_Int64(std::int64_t v) { return rivet::Value(v); }
inline rivet::Value encode_String(std::string const& v) { return rivet::Value(v); }
inline rivet::Value encode_AccountInfo(AccountInfo const& v) { rivet::Value::List r; r.reserve(3); r.push_back(encode_String(v.id)); r.push_back(encode_String(v.path)); r.push_back(encode_String(v.size_label)); return rivet::Value(std::move(r)); }
inline rivet::Value encode__List_AccountInfo_(std::vector<AccountInfo> const& xs) { rivet::Value::List r; r.reserve(xs.size()); for (auto const& x : xs) r.push_back(encode_AccountInfo(x)); return rivet::Value(std::move(r)); }
inline rivet::Value encode_SnapshotInfo(SnapshotInfo const& v) { rivet::Value::List r; r.reserve(5); r.push_back(encode_Int64(v.index)); r.push_back(encode_String(v.created_at)); r.push_back(encode_String(v.account)); r.push_back(encode_Int64(v.file_count)); r.push_back(encode_String(v.total_label)); return rivet::Value(std::move(r)); }
inline rivet::Value encode__List_SnapshotInfo_(std::vector<SnapshotInfo> const& xs) { rivet::Value::List r; r.reserve(xs.size()); for (auto const& x : xs) r.push_back(encode_SnapshotInfo(x)); return rivet::Value(std::move(r)); }
inline rivet::Value encode_Bool(bool v) { return rivet::Value(v); }
inline rivet::Value encode_OperationResult(OperationResult const& v) { rivet::Value::List r; r.reserve(2); r.push_back(encode_Bool(v.ok)); r.push_back(encode_String(v.message)); return rivet::Value(std::move(r)); }
inline rivet::Value encode_Void() { return rivet::Value{}; }

inline std::int64_t decode_Int64(rivet::Value const& v) { if (auto p = std::get_if<std::int64_t>(&v.data)) return *p; throw std::runtime_error("Rivet result type mismatch: Int64"); }
inline std::string decode_String(rivet::Value const& v) { if (auto p = std::get_if<std::string>(&v.data)) return *p; throw std::runtime_error("Rivet result type mismatch: String"); }
inline AccountInfo decode_AccountInfo(rivet::Value const& v) { auto p = std::get_if<rivet::Value::List>(&v.data); if (!p || p->size() != 3) throw std::runtime_error("Rivet result type mismatch: AccountInfo"); return AccountInfo{decode_String((*p)[0]), decode_String((*p)[1]), decode_String((*p)[2])}; }
inline std::vector<AccountInfo> decode__List_AccountInfo_(rivet::Value const& v) { auto p = std::get_if<rivet::Value::List>(&v.data); if (!p) throw std::runtime_error("Rivet result type mismatch: (List AccountInfo)"); std::vector<AccountInfo> r; r.reserve(p->size()); for (auto const& x : *p) r.push_back(decode_AccountInfo(x)); return r; }
inline SnapshotInfo decode_SnapshotInfo(rivet::Value const& v) { auto p = std::get_if<rivet::Value::List>(&v.data); if (!p || p->size() != 5) throw std::runtime_error("Rivet result type mismatch: SnapshotInfo"); return SnapshotInfo{decode_Int64((*p)[0]), decode_String((*p)[1]), decode_String((*p)[2]), decode_Int64((*p)[3]), decode_String((*p)[4])}; }
inline std::vector<SnapshotInfo> decode__List_SnapshotInfo_(rivet::Value const& v) { auto p = std::get_if<rivet::Value::List>(&v.data); if (!p) throw std::runtime_error("Rivet result type mismatch: (List SnapshotInfo)"); std::vector<SnapshotInfo> r; r.reserve(p->size()); for (auto const& x : *p) r.push_back(decode_SnapshotInfo(x)); return r; }
inline bool decode_Bool(rivet::Value const& v) { if (auto p = std::get_if<bool>(&v.data)) return *p; throw std::runtime_error("Rivet result type mismatch: Bool"); }
inline OperationResult decode_OperationResult(rivet::Value const& v) { auto p = std::get_if<rivet::Value::List>(&v.data); if (!p || p->size() != 2) throw std::runtime_error("Rivet result type mismatch: OperationResult"); return OperationResult{decode_Bool((*p)[0]), decode_String((*p)[1])}; }
inline void decode_Void(rivet::Value const& v) { if (!std::holds_alternative<std::monostate>(v.data)) throw std::runtime_error("Rivet result type mismatch: Void"); }
}  // namespace detail

struct NotificationEvent { std::string value; };
struct Snapshots_changedEvent { std::string value; };
using Event = std::variant<NotificationEvent, Snapshots_changedEvent>;
inline Event decode_event(std::string const& name, rivet::Value const& value) {
  if (name == "notification") return Event{NotificationEvent{detail::decode_String(value)}};
  if (name == "snapshots-changed") return Event{Snapshots_changedEvent{detail::decode_String(value)}};
  throw std::runtime_error("unknown Rivet event: " + name);
}

class API {
 public:
  explicit API(rivet::linux_runtime::Backend& backend) : backend_(backend) {}

  std::future<std::int64_t> get_auto_snapshot() { auto raw = backend_.call("get-auto-snapshot", rivet::Value::List{}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> std::int64_t { return detail::decode_Int64(raw.get()); }); }
  [[nodiscard]] std::uint64_t get_auto_snapshot_async(std::function<void(Result<std::int64_t>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("get-auto-snapshot", rivet::Value::List{}, [completion = std::move(completion)](rivet::linux_runtime::CallResult raw) mutable { Result<std::int64_t> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode_Int64(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<std::string> get_repository_location() { auto raw = backend_.call("get-repository-location", rivet::Value::List{}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> std::string { return detail::decode_String(raw.get()); }); }
  [[nodiscard]] std::uint64_t get_repository_location_async(std::function<void(Result<std::string>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("get-repository-location", rivet::Value::List{}, [completion = std::move(completion)](rivet::linux_runtime::CallResult raw) mutable { Result<std::string> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode_String(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<std::vector<AccountInfo>> list_accounts() { auto raw = backend_.call("list-accounts", rivet::Value::List{}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> std::vector<AccountInfo> { return detail::decode__List_AccountInfo_(raw.get()); }); }
  [[nodiscard]] std::uint64_t list_accounts_async(std::function<void(Result<std::vector<AccountInfo>>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("list-accounts", rivet::Value::List{}, [completion = std::move(completion)](rivet::linux_runtime::CallResult raw) mutable { Result<std::vector<AccountInfo>> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode__List_AccountInfo_(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<std::vector<SnapshotInfo>> list_snapshots(std::string account_id) { auto raw = backend_.call("list-snapshots", rivet::Value::List{detail::encode_String(account_id)}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> std::vector<SnapshotInfo> { return detail::decode__List_SnapshotInfo_(raw.get()); }); }
  [[nodiscard]] std::uint64_t list_snapshots_async(std::string account_id, std::function<void(Result<std::vector<SnapshotInfo>>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("list-snapshots", rivet::Value::List{detail::encode_String(account_id)}, [completion = std::move(completion)](rivet::linux_runtime::CallResult raw) mutable { Result<std::vector<SnapshotInfo>> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode__List_SnapshotInfo_(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<OperationResult> restore_snapshot(std::string account_id, std::int64_t index, std::string target) { auto raw = backend_.call("restore-snapshot", rivet::Value::List{detail::encode_String(account_id), detail::encode_Int64(index), detail::encode_String(target)}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> OperationResult { return detail::decode_OperationResult(raw.get()); }); }
  [[nodiscard]] std::uint64_t restore_snapshot_async(std::string account_id, std::int64_t index, std::string target, std::function<void(Result<OperationResult>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("restore-snapshot", rivet::Value::List{detail::encode_String(account_id), detail::encode_Int64(index), detail::encode_String(target)}, [completion = std::move(completion)](rivet::linux_runtime::CallResult raw) mutable { Result<OperationResult> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode_OperationResult(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<OperationResult> run_snapshot(std::string account_id) { auto raw = backend_.call("run-snapshot", rivet::Value::List{detail::encode_String(account_id)}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> OperationResult { return detail::decode_OperationResult(raw.get()); }); }
  [[nodiscard]] std::uint64_t run_snapshot_async(std::string account_id, std::function<void(Result<OperationResult>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("run-snapshot", rivet::Value::List{detail::encode_String(account_id)}, [completion = std::move(completion)](rivet::linux_runtime::CallResult raw) mutable { Result<OperationResult> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode_OperationResult(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<void> set_auto_snapshot(std::int64_t minutes) { auto raw = backend_.call("set-auto-snapshot", rivet::Value::List{detail::encode_Int64(minutes)}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> void { detail::decode_Void(raw.get()); }); }
  [[nodiscard]] std::uint64_t set_auto_snapshot_async(std::int64_t minutes, std::function<void(Result<void>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("set-auto-snapshot", rivet::Value::List{detail::encode_Int64(minutes)}, [completion = std::move(completion)](rivet::linux_runtime::CallResult raw) mutable { Result<void> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); detail::decode_Void(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<void> set_repository_location(std::string path) { auto raw = backend_.call("set-repository-location", rivet::Value::List{detail::encode_String(path)}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> void { detail::decode_Void(raw.get()); }); }
  [[nodiscard]] std::uint64_t set_repository_location_async(std::string path, std::function<void(Result<void>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("set-repository-location", rivet::Value::List{detail::encode_String(path)}, [completion = std::move(completion)](rivet::linux_runtime::CallResult raw) mutable { Result<void> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); detail::decode_Void(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }

  // Shared state
  std::future<std::int64_t> get_auto_snapshot_minutes() { auto raw = backend_.get_state("auto-snapshot-minutes"); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> std::int64_t { return detail::decode_Int64(raw.get()); }); }
  [[nodiscard]] std::uint64_t get_auto_snapshot_minutes_async(std::function<void(Result<std::int64_t>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.get_state_async("auto-snapshot-minutes", [completion = std::move(completion)](rivet::linux_runtime::CallResult raw) mutable { Result<std::int64_t> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode_Int64(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<std::int64_t> set_auto_snapshot_minutes(std::int64_t value) { auto raw = backend_.set_state("auto-snapshot-minutes", detail::encode_Int64(value)); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> std::int64_t { return detail::decode_Int64(raw.get()); }); }
  [[nodiscard]] std::uint64_t set_auto_snapshot_minutes_async(std::int64_t value, std::function<void(Result<std::int64_t>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.set_state_async("auto-snapshot-minutes", detail::encode_Int64(value), [completion = std::move(completion)](rivet::linux_runtime::CallResult raw) mutable { Result<std::int64_t> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode_Int64(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<std::string> get_repo_root() { auto raw = backend_.get_state("repo-root"); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> std::string { return detail::decode_String(raw.get()); }); }
  [[nodiscard]] std::uint64_t get_repo_root_async(std::function<void(Result<std::string>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.get_state_async("repo-root", [completion = std::move(completion)](rivet::linux_runtime::CallResult raw) mutable { Result<std::string> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode_String(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<std::string> set_repo_root(std::string value) { auto raw = backend_.set_state("repo-root", detail::encode_String(value)); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> std::string { return detail::decode_String(raw.get()); }); }
  [[nodiscard]] std::uint64_t set_repo_root_async(std::string value, std::function<void(Result<std::string>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.set_state_async("repo-root", detail::encode_String(value), [completion = std::move(completion)](rivet::linux_runtime::CallResult raw) mutable { Result<std::string> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode_String(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }

 private:
  rivet::linux_runtime::Backend& backend_;
};

}  // namespace rivet_app
